version: '3'

services:
  python-server:
    build: 
      context: ./python-server
      dockerfile: ./Dockerfile
    env_file: ./.env 
    ports:
      - "5000:5000"
  easy-trip:
    build: 
      context: .
      dockerfile: ./Dockerfile 
    env_file: ./.env 
    ports:
      - "3000:3000"
    
